Demo/Models/ErrorViewModel.cs
namespace Gridazor.Demo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Demo/Models/IndexVM.cs
namespace Gridazor.Demo.Models;

public class IndexVM
{
    public List<Product> Products { get; set; } = [];
}

Demo/Models/Product.cs
using Gridazor.Abstractions;
using Gridazor.Attributes;
using Gridazor.Statics;

namespace Gridazor.Demo.Models;

public class Product
{
    [Editable(false)]
    [Hide]
    [Required(false)]
    public Guid Id { get; set; } = Guid.NewGuid();

    [RowSelection]
    [Required(true)]
    public string Name { get; set; } = string.Empty;

    public bool Selected { get; set; }

    public DateOnly Date { get; set; }
    public DateTime DateTime { get; set; }

    [CellEditor(CellEditor.AgLargeTextCellEditor)]
    public string? Description { get; set; }

    [HeaderName("Category")]
    public int CatId { get; set; }

    [HeaderName("Sub Category")]
    public int SubCatId { get; set; }

    [Required(true)]
    public FileInput? Image { get; set; }
    public double Price { get; set; }
    public int Quantity { get; set; }
    public Quality Quality { get; set; }
}

public enum Quality
{
    Low,
    Medium, 
    High
}

public class FileInput : IFileInput
{
    public IFormFile? File { get; set; }
    public string? Name { get; set; }
    public string? Path { get; set; }
}

Demo/Models/SelectDto.cs
namespace Gridazor.Demo.Models;

public record SelectDto(int Id, string Name);

Demo/Models/Test.cs
using Gridazor.Attributes;
using Gridazor.Models;

namespace Gridazor.Demo.Models;

public class Test
{
    [Field("id")]
    [HeaderName("Id")]
    [Editable(false)]
    [Hide]
    [Required(false)]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Field("name")]
    [HeaderName("Name")]
    [Editable(true)]
    [RowSelection]
    public string Name { get; set; } = string.Empty;

    [Field("description")]
    [HeaderName("Description")]
    [Editable(true)]
    [CellEditor("agLargeTextCellEditor")]
    public string? Description { get; set; }

    public int CatId { get; set; }

    public FileInput? Image { get; set; }
}

public class FileInput : IFileInput
{
    public IFormFile? File { get; set; }
    public string? Name { get; set; }
    public string? Path { get; set; }
}

Demo/Controllers/CultureController.cs
using Gridazor.Demo.Utilities;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace Gridazor.Demo.Controllers;

public class CultureController : Controller
{
    public IActionResult SetLanguage(string culture, string returnUrl)
    {
        if (!LanguageKeys.Get().Contains(culture))
        {
            culture = LanguageKeys.En;
        }

        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions
            {
                Expires = DateTimeOffset.UtcNow.AddYears(1)
            }
        );

        return LocalRedirect(returnUrl);
    }
}

Demo/Controllers/HomeController.cs
using Gridazor.Demo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gridazor.Demo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly static List<Product> _products = 
    [
        new Product() 
        {
            Id = Guid.NewGuid(),
            Name = "Name 1",
            Description = "Description 1",
            CatId = 2,
            SubCatId = 3,
            Image = new FileInput()
            {
                Name = "Image 1",
                Path = "/images/dark.png"
            },
            Date = DateOnly.MaxValue,
            Selected = false,
            Price = 100.23,
            Quantity = 5,
            Quality = Quality.High,
            DateTime = DateTime.Now
        },
        new Product() 
        {
            Id = Guid.NewGuid(),
            Name = "Name 2",
            Description = "Description 2",
            CatId = 1,
            SubCatId = 2,
            Image = new FileInput()
            {
                Name = "Image 2",
                Path = "/images/dark.png"
            },
            Date = DateOnly.MaxValue,
            Selected = false,
            Price = 10.11,
            Quantity = 1,
            Quality = Quality.Low,
            DateTime = DateTime.Now
        }
    ];

    public HomeController(ILogger<HomeController> logger) => _logger = logger;

    [HttpGet]
    public IActionResult Index()
    {
        ViewBag.Cats = new List<SelectDto>()
        {
            new(1, "Category 1"),
            new(2, "Category 2")
        };

        var subCats = new List<SubCategory>()
        {
            new(1, "Sub Cat 1-1", 1),
            new(2, "Sub Cat 1-2", 1),
            new(3, "Sub Cat 2-1", 2),
            new(4, "Sub Cat 2-2", 2),
        };

        ViewBag.SubCategories = subCats;

        ViewBag.QualityList = Enum.GetValues<Quality>()
            .Select(x => new SelectDto((int)x, x.ToString()))
            .ToList();

        return View(new IndexVM()
        {
            Products = _products
        });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(IndexVM indexVM)
    {
        _products.Clear();
        foreach (var item in indexVM.Products)
        {
            await UploadFile(item);

            _products.Add(item);
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult GetCategories(string search)
    {
        var cats = new List<SelectDto>()
        {
            new(1, "Category 1"),
            new(2, "Category 2"),
        };

        return Json(cats.Where(x => string.IsNullOrEmpty(search) || x.Name.Contains(search)).Select(x =>
            new {
                text = x.Name,
                value = x.Id
            }));
    }

    [HttpGet]
    public IActionResult GetSubCategories(int categoryId, string search)
    {
        var subCats = new List<SubCategory>()
        {
            new(1, "Sub Cat 1-1", 1),
            new(2, "Sub Cat 1-2", 1),
            new(3, "Sub Cat 2-1", 2),
            new(4, "Sub Cat 2-2", 2),
        };

        return Json(subCats
            .Where(x => string.IsNullOrEmpty(search) || x.Name.Contains(search))
            .Where(x => x.CatId == categoryId)
            .Select(x =>
                new {
                    text = x.Name,
                    value = x.Id
                }));
    }

    record SubCategory(int Id, string Name, int CatId);

    private static async Task UploadFile(Product item)
    {
        if (item.Image?.File == null || item.Image.File.Length == 0)
        {
            return;
        }

        var fileName = Path.GetFileName(item.Image.File.FileName);
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

        Directory.CreateDirectory(Path.GetDirectoryName(filePath));

        using (var stream = new FileStream(filePath, FileMode.Create))
        {
            await item.Image.File.CopyToAsync(stream);
        }

        item.Image.Path = "images/" + fileName;
        item.Image.Name = fileName;
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Demo/Views/Home/Index.cshtml
@model IndexVM
@using Gridazor;
@inject IViewLocalizer viewLocalizer;
@using System.Globalization
@using Gridazor.Attributes
@using Gridazor.Models
@using Microsoft.AspNetCore.Mvc.Localization
@{
    string rtl = CultureInfo.CurrentCulture.TextInfo.IsRightToLeft.ToString().ToLower();
}

<div class="card card-primary">
    @using (Html.BeginForm("Index", "Home", FormMethod.Post, new
    {
        enctype = "multipart/form-data"
    }))
    {
        <div class="card-header">
            <button id="add-button" type="button" class="btn btn-primary">Add</button>
            <button id="delete-button" type="button" class="btn btn-danger">Delete</button>
        </div>
        <div class="card-body">
            @Html.GridEditorFor(x => x.Products, "myGrid", "ag-theme-quartz", new Dictionary<string, Func<Column, object>>()
            {
                { nameof(HeaderNameAttribute), (column) => viewLocalizer[column.HeaderName].Value },
            })
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    }
</div>


@section Scripts{
    <script>
        const categories = @Html.Raw(Json.Serialize(ViewBag.Cats))
        const subCategories = @Html.Raw(Json.Serialize(ViewBag.SubCategories))
        const qualityList = @Html.Raw(Json.Serialize(ViewBag.QualityList))
        const gridElement = document.querySelector('#myGrid');
        const gridazor = new Gridazor(gridElement, {
            propertyName: '@nameof(Model.Products)',
            localeText: '@rtl' == 'true' ? {
                pageSizeSelectorLabel: 'حجم الصفحة:',
                page: 'الصفحة',
                to: 'إلى',
                of: 'من'
            } : {},
            enableRtl: '@rtl' == 'true',
            overrideColumnDefs: [
                {
                    field: "catId",
                    cellEditor: GridazorDropdown,
                    cellEditorParams: {
                        values: categories.map(item => ({
                            value: item.id,
                            text: item.name
                        }))
                    },
                    onCellValueChanged: (params) => gridazorDropdownHelper.resetDependentValue(params, 'subCatId'),
                    valueFormatter: (params) => gridazorDropdownHelper.valueFormatter(params)
                },
                {
                    field: "subCatId",
                    cellEditor: GridazorDropdown,
                    cellEditorParams: params => {
                        return {
                            searchUrl: "Home/GetSubCategories?categoryId=" + params.data.catId,
                            values: subCategories.filter(item => item.catId === params.data.catId).map(item => ({
                                value: item.id,
                                text: item.name
                            })) // Initial values based on current selection
                        };
                    },
                    valueFormatter: (params) => gridazorDropdownHelper.valueFormatter(params)
                },
                {
                    field: "dateTime",
                    valueGetter: p => gridazorDateInputHelper.valueGetter(p)
                },
                {
                    field: "quality",
                    cellEditor: GridazorDropdown,
                    cellEditorParams: {
                        values: qualityList.map(item => ({
                            value: item.id,
                            text: item.name
                        }))
                    },
                    valueFormatter: (params) => gridazorDropdownHelper.valueFormatter(params)
                },
                {
                    field: "image",
                    cellEditor: GridazorFileInput,
                    cellEditorParams:{

                    },
                    cellRenderer: (params) => gridazorFileInputHelper.cellRender(params)
                },
                {
                    field: "price",
                    cellEditorParams: {
                        min: 0,
                        max: 10000,
                        precision: 2
                    }
                },
                {
                    field: "quantity",
                    cellEditorParams: {
                        min: 1,
                        max: 100,
                        precision: 0
                    }
                }
            ],
            enableDelete: true,
            deleteButtonId: "delete-button",
            addByButton: true,
            addButtonId: "add-button"
        });

        document.addEventListener('rowsAfterChanging', function (e) {
        });

        document.addEventListener('rowUpdated', function (e) {
        });

        document.addEventListener('rowAdded', function (e) {
        });

        document.addEventListener('rowDeleted', function (e) {
        });

        document.addEventListener('gridazorCellValueChanged', function (e) {
        });
    </script>
}

Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/gridazor/gridazor.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            @{
                                var URL = Context.Request.Path + Context.Request.QueryString;
                            }
                            <a href="@Url.Action("SetLanguage","Culture",new{ returnUrl= URL, culture="en"})" class="dropdown-item">English</a>
                            <a href="@Url.Action("SetLanguage","Culture",new{ returnUrl= URL, culture="ar"})" class="dropdown-item">العربية</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/ag-grid-community/dist/ag-grid-community.min.js"></script>
    <script src="~/lib/gridazor/gridazor.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>